[project]
name = "pkm-storage-runtime"
version = "0.1.0"
description = "Runtime dependencies for this PKM storage"
requires-python = ">=3.12"
dependencies = ["pkm-framework"]

[tool.uv]
package = false

[tool.uv.sources]
pkm-framework = { git = "https://github.com/Seika139/pkm-framework.git", tag = "v0.1.3" }
